# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestLogin():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_login(self):
    self.driver.get("http://localhost:8003/")
    self.driver.set_window_size(1366, 728)
    self.driver.find_element(By.CSS_SELECTOR, ".input-group:nth-child(1) > #email").click()
    self.driver.find_element(By.CSS_SELECTOR, ".input-group:nth-child(1) > #email").send_keys("shivamsharma@gmail.com")
    self.driver.find_element(By.CSS_SELECTOR, ".input-group:nth-child(2) > #password").click()
    self.driver.find_element(By.CSS_SELECTOR, ".input-group:nth-child(2) > #password").send_keys("21bcaf55")
    self.driver.find_element(By.CSS_SELECTOR, ".input-group:nth-child(2) > #password").send_keys(Keys.ENTER)
    self.driver.find_element(By.LINK_TEXT, "Logout").click()
  
